# Generated by Django 4.1.4 on 2022-12-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('useremail', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('usertext', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'پیام های کاربران',
                'verbose_name_plural': 'پیام های کاربران',
            },
        ),
    ]
